name: labeling

on: 
  issues: 
    types:
      - reopened
      - opened

jobs:
  label_issues:
    runs-on: ubuntu-lates
    permissions:
      issues: write
    steps:
      - name: Label issues
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: "triage"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
